class_name MobChaseReplay
extends RefCounted
## Replays #357's authoritative mob-chase fixture through ZoneConnection.
##
## The frames are generated by `server/wire/mob_chase_stream_test.go` from the
## real World.Step + wire encoder path. This helper supplies only the transport
## timing a deterministic capture needs: each `advance()` presents one binary
## frame to the shipped connection pump. Wire decoding, stream validation and
## table mutation remain owned by ZoneConnection and ReplicaStore.

const FIXTURE_PATH := "res://tests/data/wire_goldens.json"
const URL := "wss://mob-chase-evidence.invalid/zone"
## Test/capture stand-in only. No server receives or verifies it.
const TOKEN := "mob-chase-evidence-token"


class FixtureTransport:
	extends RefCounted

	var ready_state := WebSocketPeer.STATE_CONNECTING
	var packets: Array[PackedByteArray] = []
	var connected_url := ""
	var handshake_headers := PackedStringArray()
	var inbound_buffer_size := 0
	var _last_was_text := false

	func connect_to_url(url: String) -> int:
		connected_url = url
		return OK

	func poll() -> void:
		pass

	func get_ready_state() -> int:
		return ready_state

	func get_available_packet_count() -> int:
		return packets.size()

	func get_packet() -> PackedByteArray:
		_last_was_text = false
		return packets.pop_front()

	func was_string_packet() -> bool:
		return _last_was_text

	func set_inbound_buffer_size(size: int) -> void:
		inbound_buffer_size = size

	func set_handshake_headers(headers: PackedStringArray) -> void:
		handshake_headers = headers

	func close() -> void:
		ready_state = WebSocketPeer.STATE_CLOSED


var _fixture: Dictionary = {}
var _frames: Array = []
var _index := 0
var _transport: FixtureTransport = null
var _connection: ZoneConnection = null
var _error := ""


func _init(path := FIXTURE_PATH) -> void:
	var text := FileAccess.get_file_as_string(path)
	if text.is_empty():
		_error = "fixture %s is missing or empty" % path
		return
	var parsed: Variant = JSON.parse_string(text)
	if parsed is not Dictionary:
		_error = "fixture %s is not a JSON object" % path
		return
	var root: Dictionary = parsed
	if root.get("mob_chase") is not Dictionary:
		_error = "fixture has no mob_chase section"
		return
	_fixture = root["mob_chase"]
	for key: String in ["observer", "mob", "target", "cast_range_mm", "frames", "stationary_control"]:
		if not _fixture.has(key):
			_error = "mob_chase fixture is missing %s" % key
			return
	if _fixture["frames"] is not Array or (_fixture["frames"] as Array).is_empty():
		_error = "mob_chase fixture has no frames"
		return
	if _fixture["stationary_control"] is not Dictionary:
		_error = "mob_chase fixture has no stationary control"
		return
	_frames = _fixture["frames"]
	for i in _frames.size():
		if _frames[i] is not Dictionary:
			_error = "mob_chase frame %d is not an object" % i
			return
		var frame: Dictionary = _frames[i]
		for key: String in ["tick", "phase", "hex"]:
			if not frame.has(key):
				_error = "mob_chase frame %d is missing %s" % [i, key]
				return
		if not ["approach", "cast_start", "cast_hold"].has(String(frame["phase"])):
			_error = "mob_chase frame %d has unknown phase %s" % [i, frame["phase"]]
			return


func is_valid() -> bool:
	return _error.is_empty()


func error_detail() -> String:
	if not _error.is_empty():
		return _error
	if _connection != null and not _connection.error().is_empty():
		return "%s: %s" % [_connection.error(), _connection.error_detail()]
	return ""


func start() -> bool:
	if not is_valid():
		return false
	_transport = FixtureTransport.new()
	_connection = ZoneConnection.new(_transport)
	var original_token := OS.get_environment(ZoneConnection.ZONE_TOKEN_ENV)
	OS.set_environment(ZoneConnection.ZONE_TOKEN_ENV, TOKEN)
	var connected := _connection.connect_to(URL)
	OS.set_environment(ZoneConnection.ZONE_TOKEN_ENV, original_token)
	if not connected:
		_error = "ZoneConnection refused the evidence transport: %s" % _connection.error_detail()
		return false
	_transport.ready_state = WebSocketPeer.STATE_OPEN
	_connection.poll()
	if not _connection.is_live():
		_error = "ZoneConnection did not reach LIVE"
		return false
	return true


func connection() -> ZoneConnection:
	return _connection


func frame_count() -> int:
	return _frames.size()


func mob_id() -> int:
	return int(_fixture.get("mob", 0))


func target_id() -> int:
	return int(_fixture.get("target", 0))


func cast_range_mm() -> int:
	return int(_fixture.get("cast_range_mm", 0))


func has_next() -> bool:
	return _index < _frames.size()


func advance() -> Dictionary:
	if _connection == null or _transport == null or not _connection.is_live():
		return {"ok": false, "error": "replay has not started"}
	if not has_next():
		return {"ok": false, "error": "replay is complete"}
	var frame: Dictionary = _frames[_index]
	var bytes := (frame["hex"] as String).hex_decode()
	if bytes.is_empty():
		return {"ok": false, "error": "frame %d is empty or not hex" % _index}
	var applied_before := _connection.frames_applied()
	_transport.packets.append(bytes)
	_connection.poll()
	if not _connection.is_live():
		return {"ok": false, "error": error_detail()}
	if _connection.frames_applied() != applied_before + 1:
		return {"ok": false, "error": "frame %d was not folded" % _index}
	_index += 1
	return {"ok": true, "tick": int(frame["tick"]), "phase": String(frame["phase"])}


func stationary_control() -> Dictionary:
	return (_fixture.get("stationary_control", {}) as Dictionary).duplicate(true)


func first_mob_state() -> Dictionary:
	return _first_entity(mob_id())


func first_target_state() -> Dictionary:
	return _first_entity(target_id())


func _first_entity(id: int) -> Dictionary:
	if _frames.is_empty():
		return {}
	var frame: Dictionary = _frames[0]
	var decoded := WireCodec.decode((frame["hex"] as String).hex_decode())
	if decoded.get("ok") != true:
		return {}
	for candidate: Variant in decoded["snapshot"]["entities"]:
		var entity: Dictionary = candidate
		if int(entity["id"]) == id:
			return entity.duplicate()
	return {}
