extends Node
## Production-verifier test for issue #582, the cryptographic substrate beneath
## signing-key certificates, revocation, and manifest signatures.
##
## The vector was generated by OpenSSL, not by Godot or this verifier. That
## independence is load-bearing: a signer and verifier that share one bug can
## otherwise agree on the wrong contract forever.
##
## Run: godot --headless --path client res://tests/update_trust_test.tscn

const VERIFIER_PATH := "res://scripts/update_trust.gd"
const VECTOR_PATH := "res://tests/data/update_trust_p256_vector.json"

var _failed := false
var _verifier: Script
var _vector: Dictionary


func _ready() -> void:
	_load_inputs()
	if _failed:
		return
	_test_independent_vector_verifies()
	_test_tampered_message_is_refused()
	_test_tampered_signature_is_refused()
	_test_noncanonical_der_signature_is_refused()
	_test_wrong_key_is_refused()
	_test_malformed_inputs_fail_closed()
	_test_unsupported_algorithm_is_refused()
	if _failed:
		return
	print("TEST PASS — the Godot-native P-256 verifier accepts the OpenSSL vector and refuses every tampering/input boundary")
	get_tree().quit(0)


func _load_inputs() -> void:
	if not ResourceLoader.exists(VERIFIER_PATH):
		_fail("%s is missing — there is no production update-signature verifier" % VERIFIER_PATH)
		return
	_verifier = load(VERIFIER_PATH)
	if _verifier == null:
		_fail("%s could not be loaded as a script" % VERIFIER_PATH)
		return
	if not FileAccess.file_exists(VECTOR_PATH):
		_fail("%s is missing — without an independent vector the test can only prove Godot agrees with itself" % VECTOR_PATH)
		return
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(VECTOR_PATH))
	if not (parsed is Dictionary):
		_fail("%s did not parse as a JSON object" % VECTOR_PATH)
		return
	_vector = parsed


## Catches deleting verification, hashing different bytes, or accepting a
## framework error as success.
func _test_independent_vector_verifies() -> void:
	var got := _verify(str(_vector["message"]), str(_vector["signature_base64"]),
		str(_vector["public_key_path"]), str(_vector["algorithm"]))
	if not bool(got.get("valid", false)) or str(got.get("error", "")) != "":
		_fail("the OpenSSL P-256/SHA-256 vector was refused: %s" % str(got.get("error", "")))


## Catches verifying a digest supplied by the manifest instead of the actual JCS
## bytes, or otherwise failing to bind the signature to its message.
func _test_tampered_message_is_refused() -> void:
	var got := _verify(str(_vector["message"]) + " ", str(_vector["signature_base64"]),
		str(_vector["public_key_path"]), str(_vector["algorithm"]))
	_expect_refused(got, "a one-byte message change")


## Catches accepting any parseable DER blob or ignoring Crypto.verify's result.
func _test_tampered_signature_is_refused() -> void:
	var raw := Marshalls.base64_to_raw(str(_vector["signature_base64"]))
	if raw.is_empty():
		_fail("the committed signature fixture did not decode")
		return
	raw[raw.size() - 1] = raw[raw.size() - 1] ^ 1
	var got := _verify(str(_vector["message"]), Marshalls.raw_to_base64(raw),
		str(_vector["public_key_path"]), str(_vector["algorithm"]))
	_expect_refused(got, "a one-bit signature change")


## Catches accepting a BER-compatible but non-DER encoding of the same valid
## signature. The r value has an unnecessary leading zero; a permissive parser
## can recover the original integer and verify it unless this boundary enforces
## DER's unique minimal representation.
func _test_noncanonical_der_signature_is_refused() -> void:
	var padded_r := _verify(str(_vector["message"]),
		str(_vector["noncanonical_r_signature_base64"]),
		str(_vector["public_key_path"]), str(_vector["algorithm"]))
	_expect_refused(padded_r, "the same signature with a non-minimal r INTEGER")

	var padded_s := _verify(str(_vector["message"]),
		str(_vector["noncanonical_s_signature_base64"]),
		str(_vector["public_key_path"]), str(_vector["algorithm"]))
	_expect_refused(padded_s, "the same signature with a non-minimal s INTEGER")


## Catches treating key parsing as verification or accidentally using a global
## key instead of the caller's pinned key.
func _test_wrong_key_is_refused() -> void:
	var got := _verify(str(_vector["message"]), str(_vector["signature_base64"]),
		str(_vector["wrong_public_key_path"]), str(_vector["algorithm"]))
	_expect_refused(got, "a different valid P-256 public key")


## Catches permissive decoders turning malformed input into empty bytes or a
## framework error that callers mistake for a verified signature.
func _test_malformed_inputs_fail_closed() -> void:
	var malformed_signature := _verify(str(_vector["message"]), "%%%",
		str(_vector["public_key_path"]), str(_vector["algorithm"]))
	_expect_refused(malformed_signature, "malformed base64")

	var malformed_key: Dictionary = _verifier.verify_signature(str(_vector["algorithm"]),
		"not a PEM public key", str(_vector["message"]).to_utf8_buffer(),
		str(_vector["signature_base64"]))
	_expect_refused(malformed_key, "a malformed public key")


## Catches algorithm confusion: a caller cannot relabel bytes and reach the same
## verification primitive.
func _test_unsupported_algorithm_is_refused() -> void:
	var got := _verify(str(_vector["message"]), str(_vector["signature_base64"]),
		str(_vector["public_key_path"]), "ed25519")
	_expect_refused(got, "an unsupported algorithm label")


func _verify(message: String, signature_base64: String, public_key_path: String,
		algorithm: String) -> Dictionary:
	var public_key := FileAccess.get_file_as_string(public_key_path)
	if public_key.is_empty():
		_fail("could not read public key fixture %s" % public_key_path)
		return {"valid": false, "error": "test fixture missing"}
	return _verifier.verify_signature(algorithm, public_key, message.to_utf8_buffer(),
		signature_base64)


func _expect_refused(got: Dictionary, case_name: String) -> void:
	if bool(got.get("valid", false)):
		_fail("%s verified successfully" % case_name)
		return
	if str(got.get("error", "")).is_empty():
		_fail("%s was refused without an error; callers could not distinguish refusal from an incomplete result" % case_name)


func _fail(message: String) -> void:
	if _failed:
		return
	_failed = true
	push_error(message)
	print("TEST FAIL — %s" % message)
	get_tree().quit(1)
