apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: world-at-ruin-zone-admission
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: world-at-ruin
    kind: SecretStore
  target:
    name: world-at-ruin-zone-admission
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: apps/world-at-ruin/admission
        property: secret
