apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pod-disruption-budget.yaml
  - password.yaml
  - push-secret.yaml
  - external-secret.yaml
