apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: world-at-ruin-zone-admission
spec:
  length: 64
  digits: 0
  symbols: 64
  symbolCharacters: "0123456789abcdef"
  noUpper: true
  allowRepeat: true
